### ISSUE TITLE
Localtuya & HA 2025.1.4

### ISSUE THREAD

**Issue by dominiklehmann070704** [mileperhour/localtuya-homeassistant#60]
Hey, the logfile show this error after update HAOS to 2025.1.4

Detected that custom integration 'localtuya' sets option flow config_entry explicitly, which is deprecated at custom_components/localtuya/config_flow.py, line 396: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/rospogrigio/localtuya/issues

and 

Setup failed for custom integration 'localtuya': Unable to import component: cannot import name 'CURRENT_HVAC_HEAT' from 'homeassistant.components.climate.const' (/usr/src/homeassistant/homeassistant/components/climate/const.py)
